const cards = {
	/*
		type=/resource|creature|weapon|shield|permanent|shard|nymph|deprecate/
	*/
	Entropy:[
		{name:"아메시스트 필러 / 아메시스트 타워 (Amethyst Pillar / Amethyst Tower)", bazzar:true, type:"resource"},
		{name:"맥스웰즈 데몬 / 맥스웰즈 데몬 (Maxwell's Demon / Maxwell's Demon)", bazzar:true, type:"creature"},
		{name:"어보미네이션 / 마이크로 어보미네이션 (Abomination / Micro Abomination)", bazzar:true, type:"creature"},
		{name:"퍼플 드래곤 / 아메시스트 드래곤 (Purple Dragon / Amethyst Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"디시페이션 실드 / 디시페이션 필드 (Dissipation Shield / Dissipation Field)", bazzar:true, type:"shield"},
		{name:"라이칸스로프 / 웨어울프 (Lycanthrope / Werewolf)", bazzar:true, type:"creature"},
		{name:"카오스 시드 / 카오스 파워 (ChaosSeed / Chaos Power)", bazzar:true, type:"spell"},
		{name:"노바 / 슈퍼노바 (Nova / Supernova)", bazzar:true, type:"spell"},
		{name:"뮤테이션 / 임프루브드 뮤테이션 (Mutation / Improved Mutation)", bazzar:true, type:"spell"},
		{name:"디스코드 / 디스코드 (Discord / Discord)", bazzar:false, type:"weapon"},
		{name:"폴른 엘프 / 폴른 드루이드 (Fallen Elf / Fallen Druid)", bazzar:true, type:"creature"},
		{name:"안티매터 / 임프루브드 안티매터 (Antimatter / Improved Antimatter)", bazzar:true, type:"spell", remarks:"alchemy"},
		{name:"버터플라이 이펙트 / 버터플라이 이펙트 (Butterfly Effect / Butterfly Effect)", bazzar:true, type:"spell"},
		{name:"판데모니엄 / 판데모니엄 (Pandemonium / Pandemonium)", bazzar:true, type:"spell"},
		{name:"슈뢰딩거즈 캣 / 슈뢰딩거즈 캣 (Schrödinger's Cat / Schrödinger's Cat)", bazzar:true, type:"creature"},
		{name:"싱귤러리티 / 싱귤러리티 (Singularity / Singularity)", bazzar:false, type:"creature"},
		{name:"퍼플 님프 / 퍼플 님프 (Purple Nymph / Purple Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 세렌디피티 / 샤드 오브 세렌디피티 (Shard of Serendipity / Shard of Serendipity)", bazzar:false, type:"shard"},
		{name:"엔트로피 펜듈럼 / 엔트로피 펜듈럼 (Entropy Pendulum / Entropy Pendulum)", bazzar:true, bazzar:true, type:"resource"}
	],
	Death:[
		{name:"본 필러 / 본 타워 (Bone Pillar / Bone Tower)", bazzar:true, type:"resource"},
		{name:"본 드래곤 / 아이보리 드래곤 (Bone Dragon / Ivory Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"바이러스 / 레트로바이러스 (Virus / Retrovirus)", bazzar:true, type:"creature"},
		{name:"플레쉬 스파이더 / 플레쉬 레클루즈 (Flesh Spider / Flesh Recluse)", bazzar:true, type:"creature"},
		{name:"벌쳐 / 콘도르 (Vulture / Condor)", bazzar:true, type:"creature"},
		{name:"스컬 실드 / 스컬 버클러 (Skull Shield / Skull Buckler)", bazzar:true, type:"shield"},
		{name:"스켈레톤 / 엘리트 스켈레톤 (Skeleton / Elite Skeleton)", bazzar:true, type:"creature"},
		{name:"본야드 / 그레이브야드 (Boneyard / Graveyard)", bazzar:true, type:"permanent"},
		{name:"포이즌 / 데들리 포이즌 (Poison / Deadly Poison)", bazzar:true, type:"spell"},
		{name:"플라그 / 임프루브드 플라그 (Plague / Improved Plague)", bazzar:true, type:"spell"},
		{name:"본 월 / 본 월 (Bone Wall / Bone Wall)", bazzar:true, type:"shield"},
		{name:"아플라톡신 / 아플라톡신 (Aflatoxin / Aflatoxin)", bazzar:true, type:"spell", remarks:"alchemy"},
		{name:"머미 / 엘리트 머미 (Mummy / Elite Mummy)", bazzar:true, type:"creature"},
		{name:"데스스토커 / 데스스토커 (Deathstalker / Deathstalker)", bazzar:true, type:"creature"},
		{name:"소울 캐쳐 / 소울 캐쳐 (Soul Catcher / Soul Catcher)", bazzar:true, type:"permanent"},
		{name:"아르세닉 / 아르세닉 (Arsenic / Arsenic)", bazzar:false, type:"weapon"},
		{name:"그레이 님프 / 데스 님프 (Grey Nymph / Death Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 새크리파이스 / 샤드 오브 새크리파이스 (Shard of Sacrifice / Shard of Sacrifice)", bazzar:false, type:"shard"},
		{name:"데스 펜듈럼 / 데스 펜듈럼 (Death Pendulum / Death Pendulum)", bazzar:true, type:"resource"}
	],
	Earth:[
		{name:"스톤 필러 / 스톤 타워 (Stone Pillar / Stone Tower)", bazzar:true, type:"resource"},
		{name:"앤트라이온 / 엘리트 앤트라이온 (Antlion / Elite Antlion)", bazzar:true, type:"creature"},
		{name:"헤머타이트 골렘 / 스틸 골렘 (Hematite Golem / Steel Golem)", bazzar:true, type:"creature"},
		{name:"스톤 드래곤 / 바살트 드래곤 (Stone Dragon / Basalt Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"티타늄 실드 / 다이아몬드 실드 (Titanium Shield / Diamond Shield)", bazzar:true, type:"shield"},
		{name:"플레이트 아머 / 헤비 아머 (Plate Armor / Heavy Armor)", bazzar:true, type:"spell"},
		{name:"노움 라이더 / 노움 젬파인더 (Gnome Rider / Gnome Gemfinder)", bazzar:true, active:"resource"},
		{name:"그래보이드 / 엘리트 그래보이드 (Graboid / Elite Graboid)", bazzar:true, type:"creature"},
		{name:"슈리커 / 엘리트 슈리커 (Shrieker / Elite Shrieker)", bazzar:true, type:"creature"},
		{name:"인챈트 아티팩트 / 프로텍트 아티팩트 (Enchant Artifact / Protect Artifact)", bazzar:true, type:"spell"},
		{name:"어스퀘이크 / 퀵샌드 (Earthquake / Quicksand)", bazzar:true, type:"spell"},
		{name:"스톤 스킨 / 그라나이트 스킨 (Stone Skin / Granite Skin)", bazzar:true, type:"spell"},
		{name:"바실리스크 블러드 / 바실리스크 블러드 (Basilisk Blood / Basilisk Blood)", bazzar:true, type:"spell", remarks:"alchemy"},
		{name:"이리듐 워든 / 바나듐 워든 (Iridium Warden / Vanadium Warden)", bazzar:true, type:"creature"},
		{name:"풀버라이저 / 풀버라이저 (Pulverizer / Pulverizer)", bazzar:false, type:"weapon"},
		{name:"어번 님프 / 어스 님프 (Auburn Nymph / Earth Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 인테그리티 / 샤드 오브 인테그리티 (Shard of Integrity / Shard of Integrity)", bazzar:false, type:"shard"},
		{name:"샤드 골렘 / 샤드 골렘 (Shard Golem / Shard Golem)", bazzar:false, type:"creature"},
		{name:"어스 펜듈럼 / 어스 펜듈럼 (Earth Pendulum / Earth Pendulum)", bazzar:true, type:"resource"}
	],
	Fire:[
		{name:"버닝 필러 / 버닝 타워 (Burning Pillar / Burning Tower)", bazzar:true, type:"resource"},
		{name:"애쉬 이터 / 브림스톤 이터 (Ash Eater / Brimstone Eater)", bazzar:true, type:"creature", active:"resource"},
		{name:"크림슨 드래곤 / 루비 드래곤 (Crimson Dragon / Ruby Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"파이어 스피릿 / 파이어 스펙터 (Fire Spirit / Fire Spectre)", bazzar:true, type:"creature"},
		{name:"파이어 볼트 / 파이어 랜스 (Fire Bolt / Fire Lance)", bazzar:true, type:"spell"},
		{name:"파이어 실드 / 파이어 버클러 (Fire Shield / Fire Buckler)", bazzar:true, type:"shield"},
		{name:"디플래그레이션 / 익스플로젼 (Deflagration / Explosion)", bazzar:true, type:"spell"},
		{name:"레인 오브 파이어 / 파이어스톰 (Rain of Fire / Fire Storm)", bazzar:true, type:"spell"},
		{name:"이몰레이션 / 크리메이션 (Immolation / Cremation)", bazzar:true, type:"spell"},
		{name:"라바 골렘 / 라바 디스트로이어 (Lava Golem / Lava Destroyer)", bazzar:true, type:"creature"},
		{name:"레이지 포션 / 레이지 엘릭서 (Rage Potion / Rage Elixir)", bazzar:true, type:"spell", remarks:"alchemy"},
		{name:"피닉스 / 마이너 피닉스 (Phoenix / Minor Phoenix)", bazzar:true, type:"creature"},
		{name:"애쉬 / 애쉬 (Ash / Ash)", bazzar:false, type:"creature"},
		{name:"세라프 / 세라프 (Seraph / Seraph)", bazzar:true, type:"creature"},
		{name:"파렌하이트 / 파렌하이트 (Fahrenheit / Fahrenheit)", bazzar:false, type:"weapon"},
		{name:"레드 님프 / 파이어 님프 (Red Nymph / Fire Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 브레이버리 / 샤드 오브 브레이버리 (Shard of Bravery / Shard of Bravery)", bazzar:false, type:"shard"},
		{name:"파이어 펜듈럼 / 파이어 펜듈럼 (Fire Pendulum / Fire Pendulum)", bazzar:true, type:"resource"}
	],
	Light:[
		{name:"라이트 필러 / 라이트 타워 (Light Pillar / Light Tower)", bazzar:true, type:"resource"},
		{name:"포톤 / 레이 오브 라이트 (Photon / Ray of Light)", bazzar:true, type:"creature", active:"resource"},
		{name:"골든 드래곤 / 라이트 드래곤 (Golden Dragon / Light Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"페가수스 / 엘리트 페가수스 (Pegasus / Elite Pegasus )", bazzar:true, type:"creature"},
		{name:"홀리 라이트 / 홀리 플래쉬 (Holy Light / Holy Flash)", bazzar:true, type:"spell"},
		{name:"솔라 쉴드 / 솔라 버클러 (Solar Shield / Solar Buckler)", bazzar:true, type:"shield"},
		{name:"리플렉티브 실드 / 미러 실드 (Reflective Shield / Mirror Shield)", bazzar:true, type:"shield"},
		{name:"호프 / 호프 (Hope / Hope)", bazzar:true, type:"shield"},
		{name:"가디언 엔젤 / 아크엔젤 (Guardian Angel / Archangel )", bazzar:true, type:"creature"},
		{name:"블레싱 / 임프루브드 블레싱 (Blessing / Improved Blessing)", bazzar:true, type:"spell"},
		{name:"루시페린 / 루시페레이스 (Luciferin / Luciferase)", bazzar:true, type:"spell", remarks:"alchemy"},
		{name:"크루세이더 / 크루세이더 (Crusader / Crusader)", bazzar:true, type:"creature"},
		{name:"생츄어리 / 생츄어리 (Sanctuary / Sanctuary)", bazzar:true, type:"permanent"},
		{name:"미라클 / 임프루브드 미라클 (Miracle / Improved Miracle)", bazzar:false, type:"spell"},
		{name:"모닝 스타 / 모닝 글로리 (Morning Star / Morning Glory)", bazzar:false, type:"weapon"},
		{name:"라이트 님프 / 라이트 님프 (Light Nymph / Light Nymph)", bazzar:false, type:"nymph"},
		{name:"홀리 카우 (Holy Cow)", bazzar:false, type:"deprecate"},
		{name:"샤드 오브 디비니티 / 샤드 오브 디비니티 (Shard of Divinity / Shard of Divinity)", bazzar:false, type:"shard"},
		{name:"라이트 펜듈럼 / 라이트 펜듈럼 (Light Pendulum / Light Pendulum)", bazzar:true, type:"resource"}
	],
	Time:[
		{name:"타임 팩토리 / 타임 타워 (Time Factory / Time Tower)", bazzar:true, type:"resource"},
		{name:"데자뷰 / 엘리트 데자뷰 (Deja Vu / Elite Deja Vu)", bazzar:true, type:"creature"},
		{name:"페이트 에그 / 페이트 에그 (Fate Egg / Fate Egg)", bazzar:true, type:"creature"},
		{name:"프로크래스티네이션 / 터틀 실드 (Procrastination / Turtle Shield)", bazzar:true, type:"shield"},
		{name:"리버스 타임 / 리와인드 (Reverse Time / Rewind)", bazzar:true, type:"spell"},
		{name:"골든 아워글래스 / 일렉트럼 아워글래스 (Golden Hourglass / Electrum Hourglass)", bazzar:true, type:"permanent"},
		{name:"데보니안 드래곤 / 실루리안 드래곤 (Devonian Dragon / Silurian Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"아누비스 / 엘리트 아누비스 (Anubis / Elite Anubis)", bazzar:true, type:"creature"},
		{name:"선다이얼 / 선다이얼 (Sundial / Sundial)", bazzar:true, type:"permanent"},
		{name:"스캐럽 / 엘리트 스캐럽 (Scarab / Elite Scarab)", bazzar:true, type:"creature"},
		{name:"프리코그니션 / 프리코그니션 (Precognition / Precognition)", bazzar:true, type:"spell", remarks:"alchemy"},
		{name:"듄 스콜피온 / 듄 스콜피온 (Dune Scorpion / Dune Scorpion)", bazzar:true, type:"creature"},
		{name:"고스트 오브 더 패스트 / 고스트 오브 더 패스트 (Ghost of the Past / Ghost of the Past)", bazzar:true, type:"creature"},
		{name:"파라오 / 파라오 (Pharaoh / Pharaoh)", bazzar:false, type:"creature"},
		{name:"이터니티 / 이터니티 (Eternity / Eternity)", bazzar:false, type:"weapon"},
		{name:"골든 님프 / 골든 님프 (Golden Nymph / Golden Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 레디니스 / 샤드 오브 레디니스 (Shard of Readiness / Shard of Readiness)", bazzar:false, type:"shard"},
		{name:"타임 펜듈럼 / 타임 펜듈럼 (Time Pendulum / Time Pendulum)", bazzar:true, type:"resource"}
	],
	Gravity:[
		{name:"그래비티 필러 / 그래비티 타워 (Gravity Pillar / Gravity Tower)", bazzar:true, type:"resource"},
		{name:"사파이어 차저 / 엘리트 차저 (Sapphire Charger / Elite Charger)", bazzar:true, type:"creature"},
		{name:"아르마지오 / 엘리트 아르마지오 (Armagio / Elite Armagio)", bazzar:true, type:"creature"},
		{name:"그래비톤 머시너리 / 그래비톤 가드 (Graviton Mercenary / Graviton Guard)", bazzar:true, type:"creature"},
		{name:"콜로설 드래곤 / 매시브 드래곤 (Colossal Dragon / Massive Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"그래비티 실드 / 그래비티 (Gravity Shield / Gravity Shield)", bazzar:true, type:"shield"},
		{name:"모멘텀 / 언스토퍼블 (Momentum / Unstoppable)", bazzar:true, type:"spell"},
		{name:"오튜그 / 엘리트 오튜그 (Otyugh / Elite Otyugh)", bazzar:true, type:"creature"},
		{name:"그래비티 풀 / 그래비티 포스 (Gravity Pull / Gravity Force)", bazzar:true, type:"spell"},
		{name:"그래비톤 파이어 이터 / 그래비톤 파이어마스터 (Graviton Fire Eater / Graviton Firemaster)", bazzar:true, type:"creature"},
		{name:"블랙홀 / 블랙홀 (Black Hole / Black Hole)", bazzar:true, type:"spell", remarks:"alchemy"},
		{name:"키메라 / 키메라 (Chimera / Chimera)", bazzar:true, type:"creature"},
		{name:"캐터펄트 / 트레뷰셋 (Catapult / Trebuchet)", bazzar:true, type:"permanent"},
		{name:"어셀러레이션 / 오버드라이브 (Acceleration / Overdrive)", bazzar:true, type:"spell"},
		{name:"그래비톤 샐비저 / 그래비톤 샐비저 (Graviton Salvager / Graviton Salvager)", bazzar:true, type:"creature"},
		{name:"타이탄 / 타이탄 (Titan / Titan)", bazzar:false, type:"weapon"},
		{name:"앰버 님프 / 그래비티 님프 (Amber Nymph / Gravity Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 포커스 / 샤드 오브 포커스 (Shard of Focus / Shard of Focus)", bazzar:false, type:"shard"},
		{name:"키메라 / 키메라 (Chimera / Chimera)", bazzar:false, type:"creature"},
		{name:"그래비티 펜듈럼 / 그래비티 펜듈럼 (Gravity Pendulum / Gravity Pendulum)", bazzar:true, type:"resource"}
	],
	Life:[
		{name:"에메랄드 필러 / 에메랄드 타워 (Emerald Pillar / Emerald Tower)", bazzar:true, type:"resource"},
		{name:"에메랄드 드래곤 / 제이드 드래곤 (Emerald Dragon / Jade Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"혼드 프로그 / 자이언트 프로그 (Horned Frog / Giant Frog)", bazzar:true, type:"creature"},
		{name:"러슬러 / 리프드래곤 (Rustler / Leaf Dragon)", bazzar:true, type:"creature", active:"resource"},
		{name:"코카트리스 / 엘리트 코카트리스 (Cockatrice / Elite Cockatrice)", bazzar:true, type:"creature"},
		{name:"포레스트 스피릿 / 포레스트 스펙쳐 (Forest Spirit / Forest Spectre)", bazzar:true, type:"creature"},
		{name:"힐 / 임프루브드 힐 (Heal / Improved Heal)", bazzar:true, type:"spell"},
		{name:"쏜 캐러페이스 / 스파인 캐러페이스 (Thorn Carapace / Spine Carapace)", bazzar:true, type:"shield"},
		{name:"에메랄드 실드 / 제이드 실드 (Emerald Shield / Jade Shield)", bazzar:true, type:"shield"},
		{name:"엠파틱 본드 / 페랄 본드 (Empathic Bond / Feral Bond)", bazzar:true, type:"permanent"},
		{name:"아드레날린 / 에피네프린 (Adrenaline / Epinephrine)", bazzar:true, type:"creature", remarks:"alchemy"},
		{name:"포레스트 스콜피온 / 스콜피온 (Forest Scorpion / Scorpion)", bazzar:true, type:"creature"},
		{name:"마이토시스 / 마이토시스 (Mitosis / Mitosis)", bazzar:true, type:"spell"},
		{name:"드루이딕 스태프 / 제이드 스태프 (Druidic Staff / Jade Staff)", bazzar:false, type:"weapon"},
		{name:"그린 님프 / 라이프 님프 (Green Nymph / Life Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 그래티튜드 / 샤드 오브 그래티튜드 (Shard of Gratitude / Shard of Gratitude)", bazzar:false, type:"shard"},
		{name:"라이프 펜듈럼 / 라이프 펜듈럼 (Life Pendulum / Life Pendulum)", bazzar:true, type:"resource"}
	],
	Air:[
		{name:"윈드 필러 / 윈드 타워 (Wind Pillar / Wind Tower)", bazzar:true, type:"resource"},
		{name:"드래곤플라이 / 댐스플라이 (Dragonfly / Damselfly)", bazzar:true, type:"creature", active:"resource"},
		{name:"와이번 / 엘리트 와이번 (Wyrm / Elite Wyrm)", bazzar:true, type:"creature"},
		{name:"아주르 드래곤 / 스카이 드래곤 (Azure Dragon / Sky Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"포그 실드 / 임프루브드 포그 (Fog Shield / Improved Fog)", bazzar:true, type:"shield"},
		{name:"윙즈 / 윙즈 (Wings / Wings)", bazzar:true, type:"shield"},
		{name:"썬더스톰 / 라이트닝 스톰 (Thunderstorm / Lightning Storm)", bazzar:true, type:"spell"},
		{name:"플라잉 웨폰 / 애니메이트 웨폰 (Flying Weapon / Animate Weapon)", bazzar:true, type:"spell"},
		{name:"파이어플라이 퀸 / 엘리트 퀸 (Firefly Queen / Elite Queen)", bazzar:true, type:"creature"},
		{name:"파이어플라이 / 엘리트 파이어플라이 (Firefly / Elite Firefly)", bazzar:true, type:"creature", active:"resource"},
		{name:"언스테이블 가스 / 언스테이블 가스 (Unstable Gas / Unstable Gas)", bazzar:true, type:"permanent", remarks:"alchemy"},
		{name:"쇼크웨이브 / 쇼크웨이브 (Shockwave / Shockwave)", bazzar:true, type:"spell"},
		{name:"스카이 블릿츠 / 스카이 블릿츠 (Sky Blitz / Sky Blitz)", bazzar:true, type:"spell"},
		{name:"오울즈 아이 / 이글즈 아이 (Owl's Eye / Eagle's Eye)", bazzar:false, type:"weapon"},
		{name:"블루 님프 / 에어 님프 (Blue Nymph / Air Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 프리덤 / 샤드 오브 프리덤 (Shard of Freedom / Shard of Freedom)", bazzar:false, type:"shard"},
		{name:"에어 펜듈럼 / 에어 펜듈럼 (Air Pendulum / Air Pendulum)", bazzar:true, type:"resource"}
	],
	Water:[
		{name:"워터 필러 / 워터 타워 (Water Pillar / Water Tower)", bazzar:true, type:"resource"},
		{name:"크리사오라 / 피살리아 (Chrysaora / Physalia)", bazzar:true, type:"creature"},
		{name:"블루 크라울러 / 어비스 크라울러 (Blue crawler / Abyss Crawler)", bazzar:true, type:"creature"},
		{name:"프리즈 / 컨질 (Freeze / Congeal)", bazzar:true, type:"spell"},
		{name:"아이스 볼트 / 아이스 랜스 (Ice Bolt / Ice Lance)", bazzar:true, type:"spell"},
		{name:"아이스 실드 / 퍼머프로스트 실드 (Ice Shield / Permafrost Shield)", bazzar:true, type:"shield"},
		{name:"퓨리파이 / 퓨리파이 (Purify / Purify)", bazzar:true, type:"spell"},
		{name:"아크틱 스퀴드 / 아크틱 옥토퍼스 (Arctic Squid / Arctic Octopus)", bazzar:false, type:"creature"},
		{name:"아이스 드래곤 / 아크틱 드래곤 (Ice Dragon / Arctic Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"토드피쉬 / 푸퍼 피쉬 (Toadfish / Puffer Fish)", bazzar:true, type:"creature"},
		{name:"마인드 플레이어 / 울리사리드 (Mind Flayer / Ulitharid)", bazzar:true, type:"creature"},
		{name:"님프스 티어즈 / 님프스 티어즈 (Nymph's Tears / Nymph's Tears)", bazzar:true, type:"spell", remarks:"alchemy"},
		{name:"플러딩 / 이눈데이션 (Flooding / Inundation)", bazzar:true, type:"permanent"},
		{name:"스팀 머신 / 스팀 머신 (Steam Machine / Steam Machine)", bazzar:true, type:"creature"},
		{name:"드라이 스펠 / 데시케이션 (Dry Spell / Desiccation)", bazzar:true, type:"spell"},
		{name:"트라이던트 / 포세이돈 (Trident / Poseidon)", bazzar:false, type:"weapon"},
		{name:"님프 퀸 / 워터 님프 (Nymph Queen / Water Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 페이션스 / 샤드 오브 페이션스 (Shard of Patience / Shard of Patience)", bazzar:false, type:"shard"},
		{name:"워터 펜듈럼 / 워터 펜듈럼 (Water Pendulum / Water Pendulum)", bazzar:true, type:"resource"}
	],
	Darkness:[
		{name:"옵시디언 필러 / 옵시디언 타워 (Obsidian Pillar / Obsidian Tower)", bazzar:true, type:"resource"},
		{name:"블랙 드래곤 / 옵시디언 드래곤 (Black Dragon / Obsidian Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"디바우러 / 페스트 (Devourer / Pest)", bazzar:true, type:"creature"},
		{name:"패러사이트 / 블러드서커 (Parasite / Bloodsucker)", bazzar:true, type:"creature"},
		{name:"더스크 맨틀 / 임프루브드 더스크 (Dusk Mantle / Improved Dusk)", bazzar:true, type:"shield"},
		{name:"스틸 / 임프루브드 스틸 (Steal / Improved Steal)", bazzar:true, type:"spell"},
		{name:"나이트폴 / 이클립스 (Nightfall / Eclipse)", bazzar:true, type:"permanent"},
		{name:"드레인 라이프 / 사이폰 라이프 (Drain Life / Siphon Life)", bazzar:true, type:"spell"},
		{name:"마이너 뱀파이어 / 뱀파이어 (Minor Vampire / Vampire)", bazzar:true, type:"creature"},
		{name:"리퀴드 섀도우 / 리퀴드 섀도우 (Liquid Shadow / Liquid Shadow)", bazzar:true, type:"spell", remarks:"alchemy"},
		{name:"가고일 / 가고일 (Gargoyle / Gargoyle)", bazzar:true, type:"creature"},
		{name:"부두 돌 / 부두 돌 (Voodoo Doll / Voodoo Doll)", bazzar:true, type:"creature"},
		{name:"나이트메어 / 나이트메어 (Nightmare / Nightmare)", bazzar:true, type:"spell"},
		{name:"클록 / 클록 (Cloak / Cloak)", bazzar:true, type:"permanent"},
		{name:"뱀파이어 스틸레토 / 뱀파이어 대거 (Vampire Stiletto / Vampire Dagger)", bazzar:false, type:"weapon"},
		{name:"블랙 님프 / 다크 님프 (Black Nymph / Dark Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 보이드 / 샤드 오브 보이드 (Shard of Void / Shard of Void)", bazzar:false, type:"shard"},
		{name:"다크 펜듈럼 / 다크 펜듈럼 (Dark Pendulum / Dark Pendulum)", bazzar:true, type:"resource"}
	],
	Aether:[
		{name:"에테르 필러 / 에테르 타워 (Aether Pillar / Aether Tower)", bazzar:true, type:"resource"},
		{name:"스파크 / 볼 라이트닝 (Spark / Ball Lightning)", bazzar:true, type:"creature"},
		{name:"라이트닝 / 썬더볼트 (Lightning / Thunderbolt)", bazzar:true, type:"spell"},
		{name:"패럴렐 유니버스 / 트윈 유니버스 (Parallel Universe / Twin Universe)", bazzar:true, type:"spell"},
		{name:"이모탈 / 엘리트 이모탈 (Immortal / Elite Immortal)", bazzar:true, type:"creature"},
		{name:"디멘져널 실드 / 페이즈 실드 (Dimensional Shield / Phase Shield)", bazzar:true, type:"shield"},
		{name:"로보토마이저 / 일렉트로커터 (Lobotomizer / Electrocutor)", bazzar:false, type:"weapon"},
		{name:"페이즈 드래곤 / 엘리트 페이즈 드래곤 (Phase Dragon / Elite Phase Dragon)", bazzar:true, type:"creature", remarks:"dragon"},
		{name:"페이즈 스파이더 / 페이즈 레클루즈 (Phase Spider / Phase Recluse)", bazzar:true, type:"creature"},
		{name:"퀸트에센스 / 퀸트에센스 (Quintessence / Quintessence)", bazzar:true, type:"spell", remarks:"alchemy"},
		{name:"프랙탈 / 프랙탈 (Fractal / Fractal)", bazzar:true, type:"spell"},
		{name:"마인드게이트 / 마인드게이트 (Mindgate / Mindgate)", bazzar:true, type:"permanent"},
		{name:"사일런스 / 사일런스 (Silence / Silence)", bazzar:true, type:"spell"},
		{name:"사이언 / 사이언 (Psion / Psion)", bazzar:true, type:"creature"},
		{name:"페이즈 샐비저 / 페이즈 샐비저 (Phase Salvager / Phase Salvager)", bazzar:true, type:"creature"},
		{name:"튀르쿠아즈 님프 / 에테르 님프 (Turquoise Nymph / Aether Nymph)", bazzar:false, type:"nymph"},
		{name:"샤드 오브 위즈덤 / 샤드 오브 위즈덤 (Shard of Wisdom / Shard of Wisdom)", bazzar:false, type:"shard"},
		{name:"에테르 펜듈럼 / 에테르 펜듈럼 (Aether Pendulum / Aether Pendulum)", bazzar:true, type:"resource"}
	],
	Others:[
		{name:"퀀텀 필러 / 퀀텀 타워 (Quantum Pillar / Quantum Tower)", bazzar:true, type:"resource"},
		{name:"샤드 오브 세렌디피티 / 샤드 오브 세렌디피티 (Shard of Serendipity / Shard of Serendipity)", bazzar:false, type:"deprecate"},
		{name:"마크 오브 엔트로피 / 마크 오브 엔트로피 (Mark of Entropy / Mark of Entropy)", bazzar:false, type:"resource"},
		{name:"실드 / 실드 (Shield / Shield)", bazzar:false, type:"deprecate"},
		{name:"웨폰 / 웨폰 (Weapon/ Weapon)", bazzar:false, type:"deprecate"},
		{name:"대거 / 더크 (Dagger / Dirk)", bazzar:true, type:"weapon"},
		{name:"숏 소드 / 롱 소드 (Short Sword / Long Sword)", bazzar:true, type:"weapon"},
		{name:"해머 / 게이블 (Hammer / Gavel)", bazzar:true, type:"weapon"},
		{name:"맬리그넌트 셀 / 맬리그넌트 셀 (Malignant Cell / Malignant Cell)", bazzar:false, type:"deprecate"},
		{name:"렐릭 / 렐릭 (Relic / Relic)", bazzar:false, type:"deprecate"},
		{name:"숏 보우 / 롱보우 (Short Bow / Longbow)", bazzar:true, type:"weapon"},
		{name:"실드 / 타워 실드 (Shield / Tower Shield)", bazzar:true, type:"shield"}
	]
}
